### ISSUE TITLE
Fixed-key AES-128 has half of each round key be all zeros

### ISSUE THREAD

**Issue by ldr709** [GaloisInc/swanky#4]
Each round key is supposed to be 128 bits long, but they are [hard-coded](https://github.com/GaloisInc/swanky/blob/master/scuttlebutt/src/aes/aes128.rs#L223) with only the low 64 bits specified.

    pub const FIXED_KEY_AES128: Aes128 = Aes128 {
        rkeys: unsafe {
            [
                (__U128 {
                    bytes: 0x15B5_32C2_F193_1C94,
                })
                .vector,
                (__U128 {
                    bytes: 0xD754_876D_FE7E_6726,
                })
                .vector,
                // ...

This means that the high 64 bits of every round key are zero. As far as I can tell, there are no AES-128 keys that expand into such a sequence of round keys. It seems likely to me that not using the proper key schedule could make AES weaker.

**Comment by amaloz** [comment]
Thanks. We'll be swapping out our custom aes implementation soon with an existing aes library, and we'll address this issue when that happens.

**Comment by amaloz** [comment]
Blocked on #5 for now.
