### ISSUE TITLE
Simple GC produces the deadlock

### ISSUE THREAD

**Issue by survived** [GaloisInc/swanky#9]
I'm developing a complex GC, and stuck in deadlock. I've managed to reduce the code causing problem, so here's a simplest circuit:

1. Both Garbler and Evaluator encode constant `a = 1 (mod 2)`
2. Garbler receives and Evaluator encodes some single value `b` (using `FancyInput::{receive, encode}`)
3. Parties evaluate `c = a ^ b`
4. GC outputs `c`, Evaluator learns its value

Code snippet is available [here](https://gist.github.com/survived/918c7b7177260ea8ddd121aa24c33abd). I'm using the latest version of the `fancy-garbling` library (e673c2 commit).

The code above produces deadlock. Specifically, Garbler freezes at step 2 (at `FancyInput::receive` value `b`), and Evaluator freezes at step 1 (while encoding the constant, it blocks at reading from a channel)

If we swap step 1 and step 2 (so parties exchange encoded value `b` first, and then encode the constant `a`), GC will terminate and produce a valid output `c`. Order of steps doesn't matter here, but matters in more complex GCs following streaming approach. 

Is it a bug or known limitation?

**Comment by spaceships** [comment]
Tracked it down. It was a buffering problem, solved by adding a flush in SyncChannel (which is used in UnixChannel). Pushed fix.

**Comment by survived** [comment]
Works great. Thank you!

**Comment by survived** [comment]
Hi @spaceships, I guess TrackChannel should flush underlying channel [here](https://github.com/GaloisInc/swanky/blob/61616ce3221f7ccf0059ae3b097baa23b3104d4b/scuttlebutt/src/channel/track_channel.rs#L74-L77) as well? Just caught deadlock in tests, fixed it locally by patching `scuttlebutt`

**Comment by spaceships** [comment]
Yes that makes sense. Fixing.
